### ISSUE TITLE
Deal with identical content in campaigns

### ISSUE THREAD

**Issue by groganz** [CampaignChain/campaignchain#223]
- [x] Check if Operation has restrictions before creating/editing
  - [x] Twitter: Tweet with same text without link in same Location since yesterday not possible.
  - [x] Facebook: Content cannot be identical with last post, but if last post is different, it can be identical with any previous posts.
    - [x] After posting to Facebook, also save link in table if in response
    - [x] If FB post includes photo, duplicate checks don't apply
- [x] Before editing repeating campaign, check whether an Operation requires a minimum interval length due to an included Operation
  - [x] Twitter: Same Tweet content only possible roughly every 24 hours (could be less, but no clear policy by Twitter)
  - [x] Facebook: Exact same post as last post only possible with shortened URLs. No difference if one post with exact same text includes a photo and the other not.
- [x] Implement duplicate content checks for REST API as well
- [x] Always shorten a link in content that is the same
  - [x] Twitter: Duplicate posts with link must have unique shortened URL. Add hash to identical URLs to get distinct shortened URLs for Bit.ly: www.example.com#1, www.example.com#2, and so on
  - [x] Facebook: Identical posts as last post with long URLs don't work, but with same shortened URL (tested with Bit.ly) it works
  - [x] [Store all URLs as CTA regardless whether they point to a connected Location](https://github.com/CampaignChain/campaignchain/issues/237)
- [ ] Add to documentation
  - [ ] new methods in handler: isExecutableInChannel(), isExecutableInCampaign()
  - [ ] handler in campaignchain.yml of Activity module
- [ ] Add new methods and params in module generator
- [ ] Check for required new params in modules installer
  - [x] "validator" for Operation module
  - [ ] "operation" for Operation module
- [x] Add schema and data update routines
- [ ] [Avoid redirect if error in new Activity](https://github.com/CampaignChain/campaignchain/issues/215)
- [ ] Add validator template to Operation module in generator
